orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_list/', views.order_list, name='order_list'),
    path('order/<int:id>/', views.order_detail, name= 'order_detail'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('search/', views.product_search, name='product_search'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

waleshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from store.models import Product
from customer.models import Customer

# Create your models here.

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def save(self, *args, **kwargs):
        if not self.order.customer:
            # Set a default customer value
            self.order.customer = Customer.objects.first()
            self.order.save()
        super().save(*args, **kwargs)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 
                  'address', 'postal_code', 'city']

orders/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import OrderItem, Order
from .forms import OrderCreateForm
from basket.basket import Basket

# Create your views here.

def order_create(request):
    try:
        basket = Basket(request)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save()
                for item in basket:
                    OrderItem.objects.create(
                        order=order,
                        product=item['product'],
                        price=item['price'],
                        quantity=item['quantity'])
                basket.clear()
            return render(request, 'orders/created.html', {'order': order})
        else:
            form = OrderCreateForm()

        context = {
            'basket': basket, 
            'form': form
            }

        return render(request, 'orders/create.html', context)
    except Exception as e:
        return HttpResponse(f"Error: {str(e)}", status=500)
    
def order_list(request):
    try:
        orders = Order.objects.all()

        return render(request, 'orders/order_list.html', {'orders' : orders})
    
    except Exception as e:
        return HttpResponse(f"Error: {str(e)}", status=500)

def order_detail(request, id):
    try:
        order = get_object_or_404(Order, id=id)
        customer = order.customer
        user = get_object_or_404(User, id=customer.pk)
        order_items = OrderItem.objects.filter(order_id=order.id)

        context = {
            'order' : order, 
            'user': user, 
            'order_items': order_items
            }

        return render(request, 'orders/order_detail.html', context)
    
    except Exception as e:
            return HttpResponse(f"Error: {str(e)}", status=500)

orders/templates/orders/create.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}

<div class="container my-5">
  <div class="row">
    <div class="col-md-6">
      <h1 class="text-center mb-5">Your Order</h1>
      <ul class="list-group">
        {% for item in basket %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ item.product.name }} x {{ item.quantity }}
          <span class="badge badge-primary badge-pill">${{ item.total_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between align-items-center font-weight-bold">
          Total
          <span class="badge badge-primary badge-pill">${{ basket.get_total_price }}</span>
        </li>
      </ul>
    </div>
    <div class="col-md-6">
      <h1 class="text-center mb-5">Billing Information</h1>
      <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Place Order" class="btn btn-primary btn-lg btn-block mt-5">
      </form>
    </div>
  </div>
</div>

{% endblock %}

orders/templates/orders/created.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}

<div class="container text-center">
    <h1 class="mb-4">Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
</div>

{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'base.html' %}

{% block title %}Order Details{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1>Order Details</h1>

        <div class="text-end mt-3">
            <a href="{% url 'orders:order_list' %}" class="btn btn-primary">Back</a>
        </div>
            
        <p class="mt-4">Order: 
            This is order <b>{{ order.id }}</b> for <b>{{ user.first_name }} {{ user.last_name }}</b>. The order was placed on: <b>{{ order.created }}</b>
        </p>
        
        <p class="mt-4">The order includes these items:</p>
        <ul class="list-group mt-4">
            {% for item in order_items %}
                <li class="list-group-item">
                    <p>Quantity: <b>{{ item.quantity }}</b></p>
                    <p>Item: <b>{{ item.product }}</b></p>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

orders/templates/orders/order_list.html
{% extends 'base.html' %}

{% block title %}Order List{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1 class="text-center mb-5">Order List</h1>

        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Placed On</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'orders:order_detail' id=order.id %}">{{ order.id }}</a></td>
                        <td>{{ order.customer.user }}</td>
                        <td>{{ order.created }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}